id: P54D8595C
initial_creation_type: input
source_metadata:
  title: Longchen Nyingtik Series
  language: fr
  description: 'Texts related to the Longchen Nyingtik (klong chen snying thig, Heart
    Essence of the Vast Expanse) cycle revealed by Rigdzin Jigme Lingpa (1729/30–1798):'
  volume:
    09fb88fafdfa476a84b9cfea6b125794:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: Aspiration Prayers
    74d912bb0aa54d6eb8e37e6d6b9342db:
      title: An Aspiration for the Final Age
      parent: Aspiration Prayers
    54f917810ad4438aa4fab00abf0af570:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: Aspiration Prayers
    b0a15e15113a40d0983d8b91b9ecf945:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Aspiration Prayers
    162c3540013d41d199c45a369214da68:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Aspiration Prayers
    46e7200a5d834fe2845af9202f86f4e1:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Aspiration Prayers
    720ba64c43244f57904f9acf1a1dffdd:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Aspiration Prayers
    05b7f5a73ede47288061c1b43bc38707:
      title: 'A Torch for the Path to Omniscience: A Word by Word Commentary to the
        Longchen Nyingtik Ngöndro'
      parent: Commentaries
    95ffe56da1874e57b8f0779265048242:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Commentaries
    d6f2aab9286944b9a57beee501151d10:
      title: 'The Casket of Siddhis: A Recitation Manual for “Vidyādhara Assembly”
        (Rigdzin Düpa)'
      parent: Commentaries
    48dfa59fe02247a6b52b8a83bc7bd2b3:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    89a10aa34ad64723a5bb4d9ec24bcf36:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Commentaries
    ef6cac99e5174d52b2826b86cc5c72f7:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    faf1a1bdd7c54095adfdd6e2ac946fbb:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Confession
    c87ee356570b4f5a99350b9b020b91ae:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Dharma Protectors
    1271340bb4894028b422d02cf8e0508a:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Dukngal Rangdrol
    e2333bb80773458394ceafa0b213f1f0:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Dukngal Rangdrol
    580359a1fe5646f293fe5778d091547d:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Dukngal Rangdrol
    41b56d48c64e47998bd4462ebdd61b7a:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Dukngal Rangdrol
    b50a60c3487341a88cb6c7fe82c94e2c:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Dukngal Rangdrol
    7ff7b4176ce441bd9e97ab393f0021a6:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Dukngal Rangdrol
    2bff3c339eb54e529615324e6348beda:
      title: 'The Loud Drum of Spring: A Commentary on the Difficult Points of the
        Ritual of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Dukngal Rangdrol
    910e9b25c92f4a5ab237bab8c4ff83e5:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Dukngal Rangdrol
    7aaf41d4f5214d2fa97fde696cde9bee:
      title: 'The Vision: A Prayer to Ārya Avalokiteśvara'
      parent: Dukngal Rangdrol
    b2b13a2ad84a43f784a2bb758080e84c:
      title: Vajra Verses on the Natural State
      parent: Dzogchen
    cd87e9f807fd43149e16ce5a5da3abd6:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Empowerment
    7c382302c3f04a17bc5095b8032682bc:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Guru Rinpoche Prayers
    4efcd1b7d7ef43c5b7fcacbfe68bc2f0:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Guru Rinpoche Prayers
    04cf84214e2d45749e4f8be4c55bd893:
      title: Guru Yoga of Rigdzin Jigme Lingpa
      parent: Guru Yoga
    ca4fd4afa077401b94c8366f6bf34599:
      title: Sādhana of the Great Master Vairotsana
      parent: Guru Yoga
    662cafa3768c4806aadc361ec82e28c6:
      title: 'The Wish-Fulfilling Jewel: The Outer Practice of Guru Yoga from the
        Heart-Essence of the Vast Expanse'
      parent: Guru Yoga
    36a72d78ed7a4c2aa2a7a7c6743e0389:
      title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the
        Heart Essence of the Vast Expanse from the Great Perfection'
      parent: Lineage Prayers
    429b3d6a07ba4b3ab4197a7f625598aa:
      title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
      parent: Lineage Prayers
    1193f24f6f6c437399fa6b6c4521414b:
      title: 'Rain of Siddhis: A Prayer to the Lineage of Rigdzin Düpa'
      parent: Lineage Prayers
    b651effc29444a6ba47625644ef1f02d:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    67d69fb98e674704a212554dc995962d:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    0a0aaf91d72f48d9a3c89a2010e495fc:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    0709d0c0110449328c88b0f44e7d9c48:
      title: Supplement to the Longchen Nyingtik Lineage Prayer
      parent: Lineage Prayers
    7b96b887a853447bb0da8c82218c9b50:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    00097c0aeda64068b0f9cb3a64a91a7f:
      title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret
        Practice of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Lineage Prayers
    b5e213f1eaca4ec69fd9d8bb36515049:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Lineage Prayers
    da47a4183607481097a26f10546260f7:
      title: Palchen Düpa Lineage Prayer
      parent: Lineage Prayers
    934a6fbd1f6f4b21b0ab5d113d38c061:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Lineage Prayers
    d47ebd730555403eaff5fe4699338e54:
      title: The Prayer for the Wrathful Guru Takhyung Barwa from the Heart Essence
        of the Vast Expanse
      parent: Lineage Prayers
    e7ef2d4697c540388655e9f913e9cdda:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    65f8cd7ca3594a469e916a7eea6cc28c:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Ngöndro
    e62cb42429234280bde382f0a0786189:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Offerings
    cee057809f3d489f9dcb04a396162cc1:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Palchen Düpa
    b71c4e0a56d5491592ebe1e1c2610f1e:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Palchen Düpa
    f5ccfb79866146dabf19ff6bee493296:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Palchen Düpa
    d2a4239b5f774071910e7c8ddfb1fa0e:
      title: Descent of Blessings of the Eight Vidyādharas
      parent: Palchen Düpa
    970872b9e37246e3aa9e175579a05506:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Palchen Düpa
    672bba4695a44af2a7a144107ab340e5:
      title: A Prayer Recalling the Life and Liberation of the Great Perfection Adept
        Rangjung Dorje (‘Naturally Arisen Vajra’), Jigme Lingpa
      parent: Prayers
    9960f7610a5a42e99da5aa92b5e09e0f:
      title: Prayer to Rigdzin Jigme Lingpa Invoking His Previous Incarnations
      parent: Prayers
    e523d07ae0b2453f98c4b6d8465b89d2:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Rigdzin Düpa
    4ad83b3a93934dc0b385f3e34638906d:
      title: Rigdzin Düpa Amṛta Offering
      parent: Rigdzin Düpa
    0fe7bb18d94c471797272d77ab1e1295:
      title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
      parent: Rigdzin Düpa
    c1bd55b18f3746d2a0476c22a03f8a7e:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Rigdzin Düpa
    d2ccea0486164b3cb07ed0a7ed75865b:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Rigdzin Düpa
    2b2ea03bf61d4544973faece4896d04a:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Rigdzin Düpa
    176fc982cf534948b6ef3a333b0c506c:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Rigdzin Düpa
    3a3beaccd4174972920e7a736ce286b8:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Root Tantra
    7f768538157f4874a49bdc916cfbc1a4:
      title: 'The Blissful Path of Action Tantra: A Ritual for Taking the One-Day
        Vows of a Lay Practitioner'
      parent: Sojong
    8f3615f9b1bf458bbe09bbf1ccacf64c:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Takhyung Barwa
    1c2eb097f8fb430aac64768d4d6dea83:
      title: A Sādhana of Tārā Sarasvatī
      parent: Tārā
    0c1a7ba5b65e4c0db4c616d698ec3d10:
      title: 'Adornment of Lord Nāgārjuna’s Wisdom Mind: The Fourfold Maṇḍala Offering
        to Tārā'
      parent: Tārā
    c9dc3eba0b1e4e948c55c8621b19fd99:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Transference (Phowa)
    4268d2b45c4942a0b55395e027480477:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    55229ff646ba4402b15e46161e8eb7e4:
      title: Notes on the Heart-Essence Practices of the Channels and Wind-Energies
      parent: Tsa Lung
    6c89f861987e421eb932333d68c76e05:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Tsok
    86c96689b2dc4b68b321c22b4b90b897:
      title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
      parent: Tummo
    316a0996fda84bccb2b17ed7f2f2ea8b:
      title: 'Cultivating the Pure Realm of Manifest Joy: A Guru Yoga of Vajrasattva'
      parent: Vajrasattva
    b74cf740a66743e7879e31463975505d:
      title: 'Lamp That Illuminates the Excellent Path of Great Bliss: A Guide to
        the Practice Text of the Female Awareness-Holder, the Queen of Great Bliss'
      parent: Yumka Dechen Gyalmo
    15e53bc801814cc5aa349b2fb0a1f6c2:
      title: 'Words of the Vajra Queen: An Essential Daily Practice of the Vidyādharas’
        Female Practice'
      parent: Yumka Dechen Gyalmo
    a6c60affd39d497885082fb0b3792e22:
      title: Yumka Fulfilment Practice
      parent: Yumka Dechen Gyalmo
    521e992a54fe4ab79036491e6ca127fb:
      title: 'The Lotus Garland: A Short Feast-Offering for the Female Practice of
        the Heart Essence of the Vast Expanse'
      parent: Yumka Dechen Gyalmo
    d2e5bc30494a4308b28b0ce69ba58464:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Yumka Dechen Gyalmo
    e9732c2f74c04d54a65c82ec05664e13:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Yumka Dechen Gyalmo
    641bdc9846864a05a6fcdd797c8ae9d3:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    0104f07c7d8e4d8591abecbaa0486aaa:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Yumka Dechen Gyalmo
    c6baa7d0c586469da2d01c85272eb404:
      title: Confession and Fulfilment Insert for Accumulating the Practice of Turning
        Back the Summons of the Ḍākinīs
      parent: Yumka Dechen Gyalmo
    fd923a1499974f68bfb4a2af03c7ddd6:
      title: 'Elucidating the Body Maṇḍala: Clarifications on the Recitation Manual
        of the Female Practice of the Queen of Great Bliss'
      parent: Yumka Dechen Gyalmo
    2c6be5e2921040d5891c6dfd74862a4c:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Yumka Dechen Gyalmo
    404a555d43934afb9c5397b95c0f3645:
      title: Main Recitation Manual for the Female Practice of the Queen of Great
        Bliss
      parent: Yumka Dechen Gyalmo
    6127e4c8a49e4387a2acec15476675a8:
      title: 'Rain of Accomplishments: A Concise Fulfilment Practice for the Female
        Awareness-Holder (Yumka)'
      parent: Yumka Dechen Gyalmo
    81c24c7b8b7d433dab1f2fef306e249b:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Yumka Dechen Gyalmo
    3503f16b0cfb4de98ccfeedfecdbf33c:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Yumka Dechen Gyalmo
created_at: '2022-03-01T04:26:19.172144'
last_modified_at: '2022-03-01T04:26:19.172147'
